kingdoms:
  ocenor:
    name: Ocenor
    world: world
    owner: Qwerty
    zones:
      bridge:
        name: Bridge
        region: bridge
      bank:
        name: Bank
        region: bank
  valhalla:
    name: Valhalla
    world: world
    owner: Azerty

wars:
  sun:
    day: 1
    startHour: 0
    startMinute: 0
    endHour: 3
    endMinute: 0